[env:nucleo_l476rg]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube

build_flags=
    ;  The tensorflowlite-micro library paths
    -Ilib/tflm_tree
    -Ilib/tflm_tree/tensorflow
    -Ilib/tflm_tree/tensorflow/lite
    -Ilib/tflm_tree/tensorflow/lite/micro
    
    ; The tensorflowlite-micro third party library paths
    -Ilib/tflm_tree/third_party/flatbuffers/include
    -Ilib/tflm_tree/third_party/gemmlowp
    -Ilib/tflm_tree/third_party/kissfft
    -Ilib/tflm_tree/third_party/ruy

    ; This is needed excluded the inclusion of the tensorflow/lite/array.h 
    ; which is not available for the cortex-m4 project build.
    -DTF_LITE_STATIC_MEMORY

    ; Define the target board as NUCLEO-L476RG (Cortex-M4 MCU).
    -DNUCLEO_L476RG

    ; The tflm build use c++17 standard
    -std=c++17

    ; Force inclusion of floating-point support in printf (e.g., %f) 
    ; which is excluded by default in many embedded libc implementations.
    ; This is needed to print the sin(x) value
    -Wl,-u,_printf_float